databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: starter
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres                     
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: myapp-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: starter 
    maxmemoryPolicy: noeviction 
    